### ISSUE TITLE
latest v2ray image

### ISSUE THREAD

**Issue by fredgit12** [SonyaCore/V2RayGen#1]
I think there is an issue related to the latest v2ray image published yesterday.
here are the docker logs:
flag provided but not defined: -config
Usage of /usr/bin/v2ray:_

**Comment by SonyaCore** [comment]
Using the latest v2ray image 

```
# docker logs 7df8c35be3ee
V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
A unified platform for anti-censorship.
2022/10/07 16:55:29 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
2022/10/07 16:55:29 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:8080
2022/10/07 16:55:29 [Warning] V2Ray 4.45.2 started
```

**Comment by fredgit12** [comment]
I could not still up the docker image,
----------   v2fly/v2fly-core   "/usr/bin/v2ray -con…"   15 seconds ago   Restarting (2) 1 second ago             root-v2ray-1
-Ubuntu 22.04.1 LTS (Jammy Jellyfish) fresh install

**Comment by fredgit12** [comment]
A new image has been published and the container is up and working fine.
Thanks
