### ISSUE TITLE
Option to add custom UUID

### ISSUE THREAD

**Issue by theStratus** [SonyaCore/V2RayGen#2]
It would be nice if we can pass the UUID as an argument. 
This way, the same client settings would be valid on a fresh installation on the same IP.

**Comment by theStratus** [comment]
The same with the NAME of the connection.

**Comment by SonyaCore** [comment]
Added --uuid , --custom-uuid 
https://github.com/SonyaCore/V2RayGen/commit/86f5ddeb980dee65a64daa0fa5328c286bf44b72
