### ISSUE TITLE
Download Failed !

### ISSUE THREAD

**Issue by a95blnd** [SonyaCore/V2RayGen#27]
hi
iam run this command in ubuntu 20.04
curl https://raw.githubusercontent.com/SonyaCore/V2RayGen/main/V2RayGen.py | sudo python3 - --vmess 

and than i got this error:

! VMESS Config Generated.
! Created xray-core docker-compose.yml configuration
Docker Not Found.
Installing Docker ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19873  100 19873    0     0   497k      0 --:--:-- --:--:-- --:--:--  497k
# Executing docker install script, commit: 4f282167c425347a931ccfd95cc91fab041d414f
+ sh -c apt-get update -qq >/dev/null
E: The repository 'http://deb.debian.org/debian $ Release' does not have a Release file.
Download Failed !

why? how i can fix this?

**Comment by SonyaCore** [comment]
If you are using ubuntu 20 you have to use ubuntu repositories for your /etc/sources.list not the Debian

Try to reinstall your server os or as a workaround check this page: https://stackoverflow.com/questions/41133455/docker-repository-does-not-have-a-release-file-on-running-apt-get-update-on-ubun

**Comment by SonyaCore** [comment]
Since there is no response from the issuer I am closing this issue.
