### ISSUE TITLE
How to run multiple configs?

### ISSUE THREAD

**Issue by miladmeidanshahi** [SonyaCore/V2RayGen#39]
Hi
Many thanks for the awesome script it is super helpful for us. I have created multiple configs like vmess, vless ... but how can I run them?

**Comment by SonyaCore** [comment]
for running multiple configs simply create each config in a directory
ex :
cd dir1
vmess service # curl .. vmess --port 4040
cd dir2 
vless service # curl .. vless --port 8080

with this, you can have multiple dockers which run on a different port.

and for view services simply use 
docker ps -a to see all running containers 

and if you want to remove a service go to the service directory and use docker-compose stop
