### ISSUE TITLE
Error on installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by theStratus** [SonyaCore/V2RayGen#4]
I am installling on Ubuntu 22.04 in Arvan. Any ideas of this error?

> ! VMess Config Generated.
! Created vmess-v2ray docker-compose.yml configuration
Docker Not Found.
Installing Docker ...
  % Total    % Received % XferdDload    AverageUpload    SpeedTotal      Time Spent       TimeLeft     Time  CurrentSpeed
0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
curl: (28) Operation timed out after 300433 milliseconds with 0 out of 0 bytes received
Failed to enable unit: Unit file docker.service does not exist.
docker-compose Not Found.
Installing docker-compose v2.11.2 ...

After upgrading all the packages. The error changed to . 

> curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to get.docker.com:443
Failed to enable unit: Unit file docker.service does not exist.
docker-compose Not Found.
Installing docker-compose v2.11.2 ...

**Comment by SonyaCore** [comment]
hi 
it tells docker is not installed in your server so the script tries to download docker with the the official script 
but your server has not had access to the docker registry servers and because of that it raises an error 

```
curl: (28) Operation timed out after 300433 milliseconds with 0 out of 0 bytes received
```
try that on a server that has an access to the docker registry

**Comment by theStratus** [comment]
Sadly true. Docker registry as well as [docker compose ](https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64) are not available. I close the issue.
