### ISSUE TITLE
Traffic limit suggestion

### ISSUE THREAD

**Issue by masanmola** [SonyaCore/V2RayGen#40]
Hi Sonya
I use this wonderful script and thank you for it.
I want to share my configs with my friends, but I'm afraid that my configs will be exposed to the public (due to resources, bandwidth, etc.).
I tried the "conlimit" option in XRayAgent but it doesn't work for me.
It would be great and more functional if there was an option to limit traffic, like "Total traffic" in the X-UI panel.

**Comment by SonyaCore** [comment]
i think the Traffic limit requires an external library to check the total traffic of the server and do something about it when it exceeds the limitation 
on x-ui i believe it was implemented with the help of gopsutil and crontab 
I will check for a solution if there anything exists to implement without requiring an external library

**Comment by masanmola** [comment]
Okay, thanks.
