### ISSUE TITLE
AGPLv3 license violation

### ISSUE THREAD

**Issue by MasterKia** [SonyaCore/V2RayGen#49]
You're using the PersianBlockerHosts filterlists as a source to block ads:

https://github.com/SonyaCore/V2RayGen/blob/f0112dd42588959975f86fd9f4d3a84c4e7deafc/utils/geodata.py#L19

That filterlist is licensed under the AGPLv3:
https://github.com/MasterKia/PersianBlocker/blob/main/PersianBlockerHosts.txt#L7

The GPL explicitly prohibits the removal of its license from files, and it appears that the listed files below do not contain any license header. Therefore, you should add the appropriate GPL license header to these files to ensure compliance with the license requirements:

https://github.com/SonyaCore/V2RayGen/blob/f0112dd42588959975f86fd9f4d3a84c4e7deafc/geodata/ads.txt

https://github.com/SonyaCore/V2RayGen/blob/f0112dd42588959975f86fd9f4d3a84c4e7deafc/geodata/clash_rules.yaml

https://github.com/SonyaCore/V2RayGen/blob/f0112dd42588959975f86fd9f4d3a84c4e7deafc/geodata/iran.dat

https://github.com/SonyaCore/V2RayGen/blob/f0112dd42588959975f86fd9f4d3a84c4e7deafc/geodata/qv2ray-client.json

The GPL also requires attribution, so please add something like this in your README file:
> The ads list is provided by the PersianBlocker list:
https://github.com/MasterKia/PersianBlocker

**Comment by SonyaCore** [comment]
Thank you for informing me 
I updated the README.md file and added block list sources 6dd75a68b25184009551a49182c211d451ee1549

**Comment by SonyaCore** [comment]
Added.
983f60e090149a2620e1dd23474177d6c92c86d8
f48e64695f4984dc488fb8fdf33a366f624d0f08
