### ISSUE TITLE
call external api after create vmess

### ISSUE THREAD

**Issue by mjmajidf** [SonyaCore/V2RayGen#6]
can you add some functionality to call external api after generating the vmess code 
 and send some data like vmess to api ?

**Comment by SonyaCore** [comment]
i can write a code to test an open connection by requesting to an external API 
maybe it's good for testing vmess connection after creating with script.

**Comment by mjmajidf** [comment]
thanks. 
please send vmess code and any other useful parameter to the external .

**Comment by SonyaCore** [comment]
hi 
after some searching, i found out there is already a project made by v2fly which is written with golang

https://github.com/v2fly/vmessping

you can use this project to test vmess connection 
because I have to reimplement this code in python which took so much time.

**Comment by mjmajidf** [comment]
thanks for your response.
but i actually want to auto create servers for some reasons. 

the v2fly project just check vmess. 

i want create new servers automatically and save vmess in external storage . 

i will wait for your changes in this project

**Comment by SonyaCore** [comment]
since this is irrelevant to how this project works I close this issue
