### ISSUE TITLE
Demote the logging level

### ISSUE THREAD

**Issue by theStratus** [SonyaCore/V2RayGen#7]
Dear Sonya 

Would you please demote the logging level in `config.json` to "error"? The default right now is "warning", that leads to bulky log files. 
```
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log", // Your path of log in Linux
    "error": "/var/log/v2ray/error.log"
  },
```

**Comment by SonyaCore** [comment]
demoted loglevel to 'warning' 132f2cc0a2fcebe34291a5fd39ea10bccb7ee12d
also, I added --loglevel --vmess-loglevel argument which you can set those values instead of 'warning' :
debug , info , warning , error , none
